---
- name: Restart sensu-backend
  service:
    name: sensu-backend
    state: restarted
  notify: Wait for sensu-backend to accept connections
  when: sensu_go_final_services.backend.state != 'stopped'

- name: Wait for sensu-backend to accept connections
  wait_for:
    port: 8081
    connect_timeout: 1

- name: Restart sensu-agent
  service:
    name: sensu-agent
    state: restarted
  when: sensu_go_final_services.agent.state != 'stopped'

- name: Update apt cache
  apt:
    update_cache: true

- name: Clean yum metadata
  command: yum clean metadata
  args:
    warn: no
