---
- name: Verify
  hosts: all
  become: true
  vars:
    inspec_download_source_dir: /usr/local/src
    inspec_bin: /opt/inspec/bin/inspec
    inspec_test_directory: "/tmp/molecule/inspec"
    inspec_downloads:
      el6:
        url: https://packages.chef.io/files/stable/inspec/4.3.2/el/6/inspec-4.3.2-1.el6.x86_64.rpm
        sha256: 7f7a4df4c0d956f38b541552c8ab2e832b2437b69b0337a67bb24fcbb807bcbe
      el7:
        url: https://packages.chef.io/files/stable/inspec/4.3.2/el/7/inspec-4.3.2-1.el7.x86_64.rpm
        sha256: 37151ff63cdbc8522f5ecd6a7d9c8bf7ca8fc68b9aad7000a40c1c9d8ba5c9b2
      ubuntu1404:
        url: https://packages.chef.io/files/stable/inspec/4.3.2/ubuntu/14.04/inspec_4.3.2-1_amd64.deb
        sha256: 343ec7b04e55aa9cb654c2925c9d40f98980d0ea376552c81582e86c7073ea8a
      ubuntu1604:
        url: https://packages.chef.io/files/stable/inspec/4.3.2/ubuntu/16.04/inspec_4.3.2-1_amd64.deb
        sha256: 343ec7b04e55aa9cb654c2925c9d40f98980d0ea376552c81582e86c7073ea8a
      ubuntu1804:
        url: https://packages.chef.io/files/stable/inspec/4.3.2/ubuntu/18.04/inspec_4.3.2-1_amd64.deb
        sha256: 343ec7b04e55aa9cb654c2925c9d40f98980d0ea376552c81582e86c7073ea8a
    inspec_package_deps:
      - lsof
      - net-tools
  tasks:
    - name: Install system dependencies for Inspec
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ inspec_package_deps }}"

    - name: Download Inspec
      get_url:
        url: "{{ inspec_downloads[inspec_version]['url'] }}"
        dest: "{{ inspec_download_source_dir }}"
        sha256sum: "{{ inspec_downloads[inspec_version]['sha256'] }}"
        mode: 0755
      register: inspec_download

    - name: Install Inspec
      yum:
        name: "{{ inspec_download.dest }}"
        state: latest
      when: ansible_pkg_mgr == 'yum'

    - name: Install Inspec
      dnf:
        name: "{{ inspec_download.dest }}"
        state: latest
      when: ansible_pkg_mgr == 'dnf'

    - name: Install Inspec
      apt:
        deb: "{{ inspec_download.dest }}"
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Create Molecule directory for test files
      file:
        path: "{{ inspec_test_directory }}"
        state: directory

    - name: Copy Inspec tests to remote
      copy:
        src: "{{ item }}"
        dest: "{{ inspec_test_directory }}/{{ item | basename }}"
      with_fileglob:
        - "{{ playbook_dir }}/tests/test_*.rb"

    - name: Register test files
      shell: "ls {{ inspec_test_directory }}/test_*.rb"
      register: test_files

    - name: Execute Inspec tests
      command: "{{ inspec_bin }} exec --chef-license accept {{ item }} --no-color --reporter progress"
      register: test_results
      with_items: "{{ test_files.stdout_lines }}"
      ignore_errors: true

    - name: Display details about the Inspec results
      debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ test_results.results }}"

    - name: Fail when tests fail
      fail:
        msg: "Inspec failed to validate"
      when: item.rc != 0
      with_items: "{{ test_results.results }}"

    - name: Execute all custom module test plays
      include_tasks: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/modules/*.yml"
