---
- name: Ensure dependencies for Sensu Go repos are installed
  dnf:
    name: "{{ sensu_go_repo_dependencies[ansible_pkg_mgr] }}"
    state: present
  when: sensu_go_manage_repo or sensu_go_manage_community_repo

- include_tasks: repo/sensu_go/{{ ansible_pkg_mgr }}.yml
  when: sensu_go_manage_repo

- include_tasks: repo/sensu_community/{{ ansible_pkg_mgr }}.yml
  when: sensu_go_manage_community_repo

- name: Flush handlers
  meta: flush_handlers
  when: sensu_go_manage_repo or sensu_go_manage_community_repo

- name: Cleanup - Remove old Sensu prerelease repos
  file:
    path: /etc/yum.repos.d/sensu_prerelease
    state: absent
  notify: Clean yum metadata
